import { useEffect, useState } from "react";
import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import type { Highlighter } from "shiki";

import { safeHref } from "../lib/viewmodel.js";

let highlighterPromise: Promise<Highlighter> | null = null;

/**
 * Shiki's web bundle keeps the highlighted-language payload small; unknown
 * languages fall back to plain text.
 */
async function getHighlighter(): Promise<Highlighter> {
  if (!highlighterPromise) {
    highlighterPromise = import("shiki/bundle/web").then(
      (shiki) =>
        shiki.createHighlighter({
          themes: ["github-light", "github-dark-dimmed"],
          langs: [
            "typescript",
            "tsx",
            "javascript",
            "jsx",
            "json",
            "bash",
            "python",
            "css",
            "html",
            "markdown",
            "diff",
            "yaml",
          ],
        }) as unknown as Highlighter,
    );
  }
  return highlighterPromise;
}

const KNOWN_LANGUAGES = new Set([
  "typescript",
  "ts",
  "tsx",
  "javascript",
  "js",
  "jsx",
  "json",
  "bash",
  "sh",
  "shell",
  "zsh",
  "python",
  "py",
  "css",
  "html",
  "markdown",
  "md",
  "diff",
  "yaml",
  "yml",
]);

const LANGUAGE_ALIASES: Record<string, string> = {
  ts: "typescript",
  js: "javascript",
  py: "python",
  sh: "bash",
  zsh: "bash",
  shell: "bash",
  yml: "yaml",
  md: "markdown",
  rs: "rust",
};

/**
 * Code highlighting with Shiki. Highlighted HTML is generated by Shiki from
 * escaped source text; model output is never injected as raw HTML.
 */
function CodeBlock({ code, language }: { code: string; language: string | null }) {
  const [html, setHtml] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    const normalized = language ? (LANGUAGE_ALIASES[language] ?? language) : null;
    if (!normalized || !KNOWN_LANGUAGES.has(normalized)) {
      setHtml(null);
      return;
    }
    getHighlighter()
      .then((highlighter) =>
        highlighter.codeToHtml(code, {
          lang: normalized,
          themes: { light: "github-light", dark: "github-dark-dimmed" },
          defaultColor: false,
        }),
      )
      .then((output) => {
        if (!cancelled) setHtml(output);
      })
      .catch(() => {
        if (!cancelled) setHtml(null);
      });
    return () => {
      cancelled = true;
    };
  }, [code, language]);

  if (html) {
    return <div className="hb-shiki" dangerouslySetInnerHTML={{ __html: html }} />;
  }
  return (
    <pre className="overflow-x-auto">
      <code>{code}</code>
    </pre>
  );
}

const remarkPlugins = [remarkGfm];

export function Markdown({ text }: { text: string }) {
  const components: Components = {
    a: ({ href, children }) => {
      const safe = safeHref(href);
      if (!safe) return <span>{children}</span>;
      const external = !safe.startsWith("#");
      return (
        <a href={safe} {...(external ? { target: "_blank", rel: "noreferrer noopener" } : {})}>
          {children}
        </a>
      );
    },
    code: ({ className, children }) => {
      const match = /language-([\w-]+)/.exec(className ?? "");
      const raw = String(children ?? "");
      if (match || raw.includes("\n")) {
        return <CodeBlock code={raw.replace(/\n$/, "")} language={match?.[1] ?? null} />;
      }
      return <code className={className}>{children}</code>;
    },
    pre: ({ children }) => <>{children}</>,
    img: ({ alt }) => {
      // Remote images inside model output are not loaded; they would leak
      // browsing metadata. Show the alt text instead.
      return <span className="text-muted">[{alt ?? "image"}]</span>;
    },
  };

  return (
    <div className="hb-markdown">
      <ReactMarkdown remarkPlugins={remarkPlugins} components={components}>
        {text}
      </ReactMarkdown>
    </div>
  );
}
